### ISSUE TITLE
Milestone 2 - Kit

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#136]
Enhance the kit to support:
- Address Book app
- Voting app (to support actions from Projects and Address Book)

**Comment by Quazia** [comment]
Projects app is currently added and being initialized, Address book has code in kit to add and initialize waiting on front end. This issue is handled for sprint 1, should be a maximum of 30 minutes work to revise this for milestone 2. Work for this issue should be handled in other branches as adding the Address book to the kit makes sense.
