### ISSUE TITLE
Projects app - "View Issue" landing page

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#267]
The View Issue landing page is the page displayed after clicking on an Issue in the Issues tab of the Projects app.

This page includes three regions:
* The summary/details of the issue
* The team region
* The activity region

This ticket involves building the front-end for this landing page alone that will display the details from Github (This does not include any of the side panels or the logic for the actions)

**Comment by Quazia** [comment]
Who is working on this currently?

**Comment by ottodevs** [comment]
I took this since it seems nobody is working on it

**Comment by ottodevs** [comment]
Totally agree @Quazia 
The current status just partially done:
- [x] Created the needed components for the Issue Detail screen
- [x] Created the logic to show/hide the Issue Detail screen, partially based on how Survey App does that (could not fully copy it because we are using the TabBar it adds some complexity, I will look more into how to do it better)
- [ ] Created initial CSS, just for the main description box, still lacks most of the layout alignment and data connection
- [ ] Side boxes: Team and activity are fully pending
- [ ] The data is coming from the Github API already, but we likely will need to get more field from the API for this detail view.

**I shifted my focus to m2-cleanup issues so I move this from "In progress" to "UI-Backlog"**

**Comment by Quazia** [comment]
Can we get an update on the status of this issue?

**Comment by stellarmagnet** [comment]
@ottodevs can you please provide update / check in code as soon as possible?
