### ISSUE TITLE
Couldnt add address book entry after clearing application cache

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#354]
I can't add address book entries after clearing the application cache

Additional, some of my previously added address book entries disappear

I cleared the application cache once, and wasn't able to reproduce, but after I did it the second time is where I saw these issues.

![image](https://user-images.githubusercontent.com/2584493/52176423-f2a3e500-27b2-11e9-8c61-33761a0082ca.png)

**Comment by stellarmagnet** [comment]
It actually looks like I am unable to perform any action in the DAO, this isnt Address Book related alone

**Comment by Quazia** [comment]
We need to look into the event handling here, this is probably another concurrency related issue.

**Comment by Quazia** [comment]
@ottodevs This should be the same part of code as #313 can you look into them together?

**Comment by ottodevs** [comment]
I figured the problem here, since we are using the address as primary key to identify each entry, when an entry is removed and another entry with the same address is added on top of it, it gets removed from the frontend on the next cache refresh since the event prompts to delete that address... I will switch to use a name+address combined primary key for the registry to solve that problem, but we would need an extra mapping to keep addresses uniqueness on the registry (the same as names).

**Comment by ottodevs** [comment]
To reproduce the problem: Create 2 addresses, clear cache, only one entry remains in the view, but in the contract the other address(es) exist, so you cannot create a new entry repeating a previous address/name...

Looking into completing the solution by cleaning up the script
