### ISSUE TITLE
Github repos are not displaying when first authorizing / the response time is not great for "new project"

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#368]
UPDATE:
Steps to reproduce: go to your Github settings on Github.com and disable the TPS app under oauth

Navigate to Projects app, authorize Github, then click New Project

The progress indicator looks good, but the problem is that it keeps saying it's loading and it never shows the repos. i had to close the panel, and then hit "new project" again, and then it loaded the repos quickly.

-------
PREVIOUS:
We need a better progress indicator when loading repos in the "New Project" side panel. Can that animation come earlier? It just seems stuck sometimes...

**Comment by ottodevs** [comment]
It seems to work better a1e4177dea8976e999df6e2899d6aeb38a9fdb75 please check out to find if it works now as expected

**Comment by stellarmagnet** [comment]
Steps to reproduce: go to your Github settings on Github.com and disable the TPS app under oauth

Navigate to Projects app, authorize Github, then click New Project

The progress indicator looks good, but the problem is that it keeps saying it's loading and it never shows the repos. i had to close the panel, and then hit "new project" again, and then it loaded the repos quickly.

**Comment by stellarmagnet** [comment]
@ottodevs were you able to successfully get the repos to load when starting fresh?

**Comment by Schwartz10** [comment]
Jotting some repro notes down:

1. sign in with github
2. add a project
3. go to the aragon app settings 
4. clear aragon cache
5. refresh projects page

-- repos aren't loading

**Comment by Schwartz10** [comment]
More notes on the problem:

https://github.com/AutarkLabs/planning-suite/blob/dev/apps/projects/app/script.js#L72 this is where the client actually _gets_ repo data.

The problem is that we're attempting to get the repo data starting here:

https://github.com/AutarkLabs/planning-suite/blob/dev/apps/projects/app/script.js#L124 (or wherever else`syncData` gets called).

The initial load of the page fires off the event logs, which fires syncData, which fires client.request, which isnt ready yet. So we lose reference to the repo in the event logs. 

One solution would be to recapture the event logs for repos and send them through the `syncData` function again. Will look into this in more depth
