### ISSUE TITLE
"web3 is not defined" on firefox

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#647]
This happened to me consistently while working on the projects app. There are calls to `web3`, which I believe are referring to the `window.web3` but its coming back as undefined on firefox

---
Yalda update:

Steps to reproduce
1) open TPS with a Firefox browser
2) Try to add a new project/repo

Observe: a panel does not open to sign a transaction. Console says "web 3 is not defined"

![image](https://user-images.githubusercontent.com/2584493/57227105-deb98a80-7010-11e9-8296-7c0252057555.png)

This is only a Firefox issue, works fine in Brave etc.

**Comment by topocount** [comment]
I've run into this issue with other providers as well. The root of the issue is that we're calling the web3 object directly in order to access web3 utils, when we should be importing these utils into our app files as standalone functions. This is the line that is causing the issue: https://github.com/AutarkLabs/planning-suite/blob/30d32cdd34a2d5a8284e507d95159c80c9be5cbf/apps/projects/app/components/App/App.js#L252
