### ISSUE TITLE
Performance issues for Projects app (Issues tab)

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#729]
There are performance issues for the Projects app, Issues tab. It is most noticeable when trying to click the checkboxes when you have the planning suite repo integrated (clicking a checkbox takes about 5 seconds for me). For smaller repos, it still takes about 1.5 seconds. I think even that is not acceptable - in comparison, clicking a checkbox in Gmail takes 1.5 milliseconds (although they do not use a real html checkbox/button component).

The browser inspector tools say the issue is related to the javascript handlers.

![image](https://user-images.githubusercontent.com/2584493/55690209-8e59f900-598e-11e9-9a9f-2770ed82dc9b.png)

**Comment by rkzel** [comment]
Quick explanation for the checkbox: its handler changes state of its parent component, list of Issues itself. When selecting an issue triggers re-rendering of the whole list, and it might involve reaching out to github to get a fresh list (via GraphQL query). Two things need to happen:
1. GraphQL needs to be moved to backend,
2. Unnecessary renders should be identified and disabled, with, most probably, memoization.

**Comment by rkzel** [comment]
What got done:
1. Checkboxes are now slow only because they are animated, and their speed is not affected by the number of issues,
2. Re-rendering of Issue Cards has been limited,

What still should be done:
1. Moving query downloading issues out of render(). It is complicated and is not expected to improve performance much immediately, but it would open possibilities of preparing data before render() - filterbar objects for example, etc.
2. Issue Card needs to be reviewed  for potential minor improvements (which can become major wins for big repos with hundreds of Cards displayed),
3. https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3
4. ...
